# Generated by Django 5.0.3 on 2024-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='educator_verified',
            field=models.BooleanField(default=False),
        ),
    ]
